#Sample configuration file for fenics_ice

[io] #Directory specification

run_name = "momsolve_init"
input_dir = "./input"
output_dir = "./output"

[constants]

rhoi = 917.0
rhow = 1030.0
g = 9.81

#random_seed = 0

[mesh]

#Not totally happy about the logic here
#A lot of fenics_ice atm is hardcoded for ismip_c

#mesh_filename = "data_mesh.xml"
data_mesh_filename = "data_mesh.xml"
data_mask_filename = "data_mask.xml"

periodic_bc = true
#what to do about these (not general):
nx = 20
ny = 20
length = 40000.0

[obs]

pts_len = 2000.0

[inversion]

active = false

max_iter = 200

alpha_active = true
beta_active = false
simultaneous = false
alt_iter = 2

gamma_alpha = 1e6
delta_alpha = 1e-2
gamma_beta = 1.0e-9
delta_beta = 1.0e-9

ftol = 1e-4
#gtol = 1e-12
verbose = true

[ice_dynamics]

sliding_law = 'linear' #weertman, linear

[momsolve]

[momsolve.picard_params]
nonlinear_solver = "newton"
[momsolve.picard_params.newton_solver]
linear_solver = "umfpack"
maximum_iterations = 200
absolute_tolerance = 1.0e-0
relative_tolerance = 1.0e-3
convergence_criterion = "incremental"
error_on_nonconvergence =  false

[momsolve.newton_params]
nonlinear_solver = "newton"
[momsolve.newton_params.newton_solver]
linear_solver = "umfpack"
maximum_iterations = 25
absolute_tolerance = 1.0e-7
relative_tolerance = 1.0e-8
convergence_criterion = "incremental"
error_on_nonconvergence = true

# #used for weertman sliding: (TODO -test)
# [momsolve.newton_params.newton_solver.lu_solver]
# same_nonzero_pattern = false
# symmetric = false
# reuse_factorization = false

[time]

run_time = 30.0
steps_per_year = 30
#total_steps = 100

[eigendec]


[errorprop]

[[boundaries]]
    name = "Left Side"
    id = 1

[[boundaries]]
    name = "Right Side"
    id = 2

[[boundaries]]
    name = "Top Edge"
    id = 3

[[boundaries]]
    name = "Bottom Edge"
    id = 4