[io] #Directory specification

#gamma_alpha =/= 1e6 (discrete cost func) but equivalent to initial test case
run_name = "smith_glacier_test"
input_dir = "./input"
output_dir = "./output"
diagnostics_dir = "./diagnostics"


# data_file = "ismipc_input.h5"
thick_data_file = "smith_bedmachine.h5"
bed_data_file = "smith_bedmachine.h5"
smb_data_file = "smith_smb.h5"
bglen_data_file = "smith_bglen.h5"
bglen_field_name = "bglen"
bglenmask_data_file = "smith_bglen.h5"
bglenmask_field_name = "bglenmask"

log_level = "error" #This is default

[constants]

rhoi = 917.0
rhow = 1030.0
g = 9.81

random_seed = 0

[mesh]

mesh_filename = "smith_variable_ocean.xdmf"
bc_filename = "smith_variable_ocean_ff.xdmf"

[[BC]]

name = "Lateral Margins" # unimportant
labels = [1]
flow_bc = "obs_vel"

[[BC]]

name = "Calving Fronts"
labels = [2, 3, 4]
flow_bc = "calving"


[obs]

vel_file = "smith_obs_vel_measures-comp.h5"

[inversion]

max_iter = 1

c1 = 1.0e-10
c2 = 0.99999990

alpha_active = true
beta_active = true

gamma_alpha = 1e2
delta_alpha = 1e-5
gamma_beta = 1.0e2
delta_beta = 1e-5
delta_beta_gnd = 3e-5

ftol = 1e-8
gtol = 1e-12
m = 200
verbose = false

delta_lbfgs = 1.0e3

#use_cloud_point_velocities = false

[ice_dynamics]

sliding_law = 'budd' #weertman, linear
min_thickness = 10.0

[momsolve]

[momsolve.picard_params]
nonlinear_solver = "newton"
[momsolve.picard_params.newton_solver]
linear_solver = "cg"
preconditioner = "hypre_amg"
maximum_iterations = 200
absolute_tolerance = 1.0e-0
relative_tolerance = 1.0e-3
convergence_criterion = "incremental"
error_on_nonconvergence =  false

[momsolve.newton_params]
nonlinear_solver = "newton"
[momsolve.newton_params.newton_solver] #[gmres w/ ilu]
linear_solver = "bicgstab" # gmres?  try direct too. [cg with icc]  [gmres, sor]
preconditioner = "hypre_amg" # doesn't work so well on unstructured mesh?
maximum_iterations = 25
absolute_tolerance = 1.0e-7
relative_tolerance = 1.0e-8
convergence_criterion = "incremental"
error_on_nonconvergence = true
[momsolve.newton_params.newton_solver.krylov_solver]
divergence_limit = 1e20
nonzero_initial_guess = false

# #used for weertman sliding: (TODO -test)
# [momsolve.newton_params.newton_solver.lu_solver]
# same_nonzero_pattern = false
# symmetric = false
# reuse_factorization = false

[time]

run_length = 10
#steps_per_year = 30
total_steps = 240
#dt = 0.0333333I33
num_sens = 5 #TODO rename


[eigendec]

num_eig = 50
eig_algo = "slepc"
misfit_only = true

#power_iter = 1 <- not used yet, saving in case
precondition_by = "prior" #prior by default

[errorprop]

qoi = 'vaf'

[invsigma]

patch_downscale = 0.1
# npatches = 100

[testing]

# expected_J_inv = 625620918.9914922 
#expected_J_inv = 566220228.1028463
expected_J_inv = 283225902.94674975
expected_Q_sigma = 5.85873469e+10
