name: test-fice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  fice-install:
    name: Install fenics_ice
    runs-on: ubuntu-latest

    steps:

      # Get fice code
      - uses: actions/checkout@v2
        with:
          path: 'fenics_ice'

      # Get tlm-adjoint code
      - uses: actions/checkout@v2
        with:
          repository: 'EdiGlacUQ/tlm_adjoint'
          path: 'tlm_adjoint'

      # Get micromamba & prerequisites
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: anaconda-client-env
          use-mamba: true

      - name: Install mamba environment from fenics_ice/environment.yml
        # if: steps.cache-conda.outputs.cache-hit != 'true'
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-name: fenics_ice
          environment-file: fenics_ice/environment.yml
          channel-priority: strict
          #auto-update-conda: true
          #use-only-tar-bz2: true # necessary for caching

      # Get conda info
      - name: mamba info
        shell: bash -l {0}
        run: |
          micromamba info
          micromamba list
          which python
          python -m pip install scipy==1.9.3

      # We install fenics_ice and tlm_adjoint as developing modules
      - name: Install repositories as dev modules
        shell: bash -l {0}
        run: |
          ls $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE/fenics_ice
          pip install -e .
          cd $GITHUB_WORKSPACE/tlm_adjoint
          pip install -e .
          micromamba info

      # Test fenics ice!
      - name: Test fice
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/fenics_ice/
          which python
          pytest -v --order-scope=module --color=yes
          mpirun -n 2 pytest -v --order-scope=module --color=yes
          mpirun -n 2 pytest -m key --key=smith --color=yes
