name: test-fenics_ice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    env:
      OMP_NUM_THREADS: 1
      OPENBLAS_NUM_THREADS: 1
    steps:
      - name: Checkout fenics_ice
        uses: actions/checkout@v4
        with:
          path: 'fenics_ice'
      - name: Checkout tlm_adjoint
        uses: actions/checkout@v4
        with:
          repository: 'tlm-adjoint/tlm_adjoint'
          path: 'tlm_adjoint'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-dolfin python3-git python3-h5py \
              python3-matplotlib python3-netcdf4 python3-numpy python3-pytest \
              python3-pytest-dependency python3-pytest-mpi \
              python3-pytest-order python3-pytest-timeout python3-scipy \
              python3-sympy python3-toml
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/tlm_adjoint
          cd fenics_ice
          pytest -v --order-scope=module --timeout=300 --timeout-method=thread
          pytest -v -k tv --order-scope=module --timeout=300 --timeout-method=thread
          mpirun -n 2 pytest -v --order-scope=module --timeout=300 --timeout-method=thread
          mpirun -n 2 pytest -m key --key=smith --timeout=300 --timeout-method=thread
